apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
  name: learner
spec: 
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWRENDQVR3Q0FRQXdEekVOTUFzR0ExVUVBd3dFWVdSaGJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQNCmdnRVBBRENDQVFvQ2dnRUJBTlcvRGoyTTRCaU1RQ2dMWlJ5b1ZBeWs4dVNXMkthUHFGTE8wZnNrcTJpZUhtYngNCm5vaXNRYlcyL3BCRjRkakNwRUpTMXpGb3NyV0tKaVpPdXJ5UHJPNnNoMll2Y09tcnR2T0NNKzBxbzlVenJBQXENCktyZ0F1UTJBdGZqTUl2RHY0dXpFblZzbVRQRlBvTGN6NDBVTWNpWW42NnE4SGFQVVhXUm9YMjZDcDJkbnRGYXINClY4ejdYTjJ0SjlZVzBUNVpSTmtPaFJJVm9YeVRsaGJaQU16cUgzRC9qUURTNC9DYmxRMS9hMEZsVGxuMUZ3c1MNCmhpTGltdXMrZ1V0VkpsbWFQSUM5c3FNdFlZcDBac3V6M3ZxRU5KenNCSW9WVnBwTEZYMk1JelhKUkdGNGN5T0INClFyK3crQWs4K09oc2RQcU5uaU9xeWVGT2tCNVVwZG5WSFJVUHNla0NBd0VBQWFBQU1BMEdDU3FHU0liM0RRRUINCkN3VUFBNElCQVFCTjJjWlJ5ekZnZ25xeDh4THhJczUxZDBScGVTdHRVK0tIOHVOZGpSQUJybWpCVWJTMEI5RVYNCmJNYUFtQXBoSVE0RTdjaHV0dGdSMGdTYnlCcWQrUDJGbk12OW04SFFVRFllelJQYVprZVhkRGdQWnNocDZHUkoNCmUwRGc5ZzdVQUVpbzR4Z0NqeHpHQlFCYm9GQmtsT3h4RXM2RnhMSjQwNEVoYk42cFZQenp2WG40dStUMkFwaU4NClpseTR2cng5clFsNzBSVWhaMFZWS3BkRmFPZGNwNG5pTWVkS1RWN3RaQmp3WkFZc2JlSVFFUXhZeE9BTzNmNHMNCkpTT1dJZy9nRkprNkJldjk1dEZtMmVlM0xvTCt3WFNSRWthbEdWSHptS2FDR1M3SlM1Q1B0ZXVxMjA1cE56TkcNCjdVeDZCV05Nb3p6dDZiT3RiaWZpMXY3SU9OWkZRM1kxDQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCg==
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 1209600 
  usages: 
  - client auth

