apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
  name: learner
spec: 
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNWekNDQVQ4Q0FRQXdFakVRTUE0R0ExVUVBd3dIYkdWaGNtNWxjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUINCkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUxtWldmYjV0WnFaamRYajNIa2ZlNVFJSWFsNEk4Y3MzMkJ5dmtYUUZvc3UNCkc0eXI1RGdUaXJCZkRZa0U0Nk8yM09RZUFxWE41dHVPeEx4QzVWdGN4YzY3WE9qM3FlRmtOQUFQRkVRY0lwOXUNCjBTN3BIazY4eHR3aThuZHpMVXhMYXU2a1c3ZGFlYnF3dWhzbkNUVGVKOTZpR2NmYUNXTER0Ym8vYVR0YSt1REUNCkQ5QTRrQkNRUlpNOCtkU1Q2WndnUXArZUdNa1AxWHBDOEtweXRFdHNkRXVPN2ZlNlEwK2M2TWIwQ3lBNUw1K0kNCkk5YXdiYmlKQXhxMGM3NldCUElxOG5YZFE5S0JHMEdRUC91NTFvaGowUDVwRzQwSXpPQW5jU2xGeDB4TWRQVTkNClprc3Y3aExVclEvSHNyK1lBck9NZ0FabktkL2IzOGk4N0h5bUNZWlpFODhDQXdFQUFhQUFNQTBHQ1NxR1NJYjMNCkRRRUJDd1VBQTRJQkFRQkdKdlFQdXc5VHBwSExkek9NZHNQbEFSeFNkaWk5WGRQQXFLZGpZRndBd3I0TDBveG0NCk9CRkVjUm9sZXBCM0xFL0Z4WkcwQXAwWWVYT3dQbEVRQU1yQVdjVldDV1BkdHNWNmJHa1BZSVdhMEZnTDlUZ08NCmM4MU9ReXZ4bmVIVjcya3lYc3psb3NmQUxGcWFWTEFsY3FEYlYyUVJSeGVGZlpKYk96d3NuWFhpclVlOHRlcVENCkRIWmVPODRKYzhmTEp3eVZaeXlvTFFEZDk3LzZOS284T0ExU1BOK1FNcFdlbzE2L2FkTTh0ajNkSkFkRm45c3gNCldGK2lzVERTNnMzeVJULzE4ZkF0VmxoL0RrU25CMHpyOWxaYzdMMHNDSkNrbzFoeEZwamdXSTJxMVZHZjRXUEoNCjg3ck5La0kwWHZzOEFPbG9DN2VRdHhSYVRrRFd1L1F6ajAwcQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 604800 
  usages: 
  - client auth

