apiVersion: v1
kind: Pod 
metadata: 
  labels: 
    env: demo 
  name: busybox 
spec: 
  containers:
  - image: busybox 
    name: busybox 
    command: ["sh", "-c", "sleep 3600"]
  restartPolicy: Never