apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-03-27T19:33:36Z"
  generation: 1
  labels:
    run: redis
    tier: backend
  name: redis
  namespace: default
  resourceVersion: "54446"
  uid: 51005416-9e27-433a-8d3a-e6eb8c165725
spec:
  containers:
  - image: redis
    name: redis-container
    #nodeName: cka-cluster2-worker # especificar en cual nodo debe de pertenecer 