apiVersion: v1
kind: Pod
metadata: 
  name: myapp 
  labels: 
    name: myapp-pod
spec: 
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo the app is runnign && sleep 3600']
    env: # asignar variables de entorno dentro del pod 
    - name: FIRSTNAME
      value: "Sebas"
  initContainers:
  - name: init-myservice 
    image: busybox:1.28 
    command: ['sh', '-c'] # un comando el cual queremos ejecutar al momento que se inicie 
    args: ['until nslookup myservice.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done'] # esto devuelve el resultado de algo
  - name: init-mydb 
    image: busybox:1.28 
    command: ['sh', '-c'] # un comando el cual queremos ejecutar al momento que se inicie 
    args: ['until nslookup mydb.default.svc.cluster.local; do echo waiting for myservice; sleep 2; done']
