apiVersion: v1
kind: Service 
metadata: 
  name: myapp
  labels: 
    env: demo 
spec: # el tipo de servicio ClusterIP viene como predefinido 
  type: NodePort
  ports: 
  - nodePort: 30001
    port: 80 # extablecer puerto 
    targetPort: 80 # exponer puerto 
  selector: 
    env: demo 