apiVersion: apps/v1 # versión del API que gestiona este recurso 
kind: ReplicaSet  # tipo del objeto que se esta creando 
metadata: 
  name: nginx-rs-task # identificador único dentro del namespace 
  labels: 
    env: demo 
spec: # define el estado deseado del recurso 
  replicas: 4 # numero deseado de pods 
  selector: # define qué pods pertenecen al replicaset 
    matchLabels: 
      env: demo
  template: # es la plantilla del pod que el rs va a clonar - cada réplica es una copia de este template 
    metadata: 
      labels: 
        env: demo # debe de considir con matchLabels 
      name: nginx 
    spec: # que es lo que se ejecutara dentro de los contenedores 
      containers: 
      - name: nginx
        image: nginx 
