apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata: 
  name: sebas
spec: 
  # va el sertificado del nuevo usuario en mi caso es sebas.csr se debe de descodifiar en base64 "cat sebas.csr | base64"
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0NCk1JSUNSVENDQVMwQ0FRQXdBRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNUUMNClpUSDJNTG05eFZleVdqay94ZXFERnpIYnlqMjFjRWZ4YXRIWGFucTBCMVduay9JenRVbFN6Z25uSmQ0VEJQRFYNCnNpQ1M4cnBlckR0eWlNMklNbkpNYldiYmVZT3hvamV4OFNCTW5mMk1zM3BjNEVObzE4RWlySm9YMExuMzJGV0sNCmpLQm5IS1hzL202WWpNeEpUTTRaRU1rNDdtZmw5Tmd6NllnMnBrVVlCRDdqMGM4RWxYSjh1cjVLMjBJWGlCNHYNCnJWS1dEQmhHWGl1ZG1aWDRDNHZXdkNHZWpjUW5yMXRRWStUcHZwQVJtaEU1N0JpekhLc2YxN1ZrOFIwbnJHaEMNCmZ4djV2UnBrVU5iWUV4azVHVUNrWmxZQTJMblhFd0hPT2JOZC81U2I4dmlQSVpoNGZCRlUyZFMvVURreDFQTTgNCjlaTFpNYmRVaS9HR1ROWjZtMmNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUE1Ynl5aWFFVEINCkZpZkMxbHBQeU1JblZja2xwbGp2U0Nqbms3ZmRaTnlWRzBNaE9WZDRTcnRCZjFpSGo0K0hxL2ExZk9hcml1UXkNCkRVMjZRRVBXa3M0YVdCVmIxaGFMSm84SkFjZyt4NUptUkJraHdsSlR0ZlBLS25ZMzBBVWNxQTV4V3NzNFAxMlYNCjFiejYzK2tnb2pIVStmSXQ2eUx6a21RemlNNTdYdytvVDlQRXNqY3huaURjQ1dpdWF2RXgvd0w4VllRTnRUa2kNCmVQaHRtNEh4VjlGL3hYdWV1QnVob2p1MHpHY0hjVmxDNmIyNkNsQlJkZm9CWEo5ZDZ4clFjMGl5RVhuNUc0YUYNClR0RS9YdEV6amlTY1JaZ1pJWnM0OWpwVm16QXhOWlRMcUFBWWJqUE5tOXBwRUQxZWhpM3AzeTcxTHZjbE9MSjYNCnVWbHhKbWdKWStGSw0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tDQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 8640000 # esto dura más de un día  
  usages: 
  - client auth

